### ISSUE TITLE
getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by donSchoe** [donSchoe/shoutcast-irc#2]
running the bot works fine, getting server status information fails though:

```
D, [2012-08-12T01:42:16.024814 #4924] DEBUG -- : RECEIVE: :qpx!~qpx@141.45.160.111 PRIVMSG #main-channel :.help
D, [2012-08-12T01:42:16.025042 #4924] DEBUG -- : SEND: PRIVMSG #main-channel :Type .np for current song or .stream for stream-url.
D, [2012-08-12T01:42:25.334546 #4924] DEBUG -- : RECEIVE: :qpx!~qpx@141.45.160.111 PRIVMSG #main-channel :.stream
D, [2012-08-12T01:42:25.334785 #4924] DEBUG -- : SEND: PRIVMSG #main-channel :Stream URL: http://example.com/listen.pls
D, [2012-08-12T01:42:29.860918 #4924] DEBUG -- : RECEIVE: :qpx!~qpx@141.45.160.111 PRIVMSG #main-channel :.np
getaddrinfo: Name or service not known
/home/af./start.rb:83em/ruby/1.8/gems/net-irc-0.0.9/lib/net/irc/client.rb:38:in `start'n `fetch'`request'on_for't'
/home/afri/.gem/ruby/1.8/gems/net-http-persistent-2.7/lib/net/http/persistent/ssl_reuse.rb:90:in `initialize': getaddrinfo: Name or service not known (SocketError)
    from /home/afri/.gem/ruby/1.8/gems/net-http-persistent-2.7/lib/net/http/persistent/ssl_reuse.rb:90:in `open'
    from /home/afri/.gem/ruby/1.8/gems/net-http-persistent-2.7/lib/net/http/persistent/ssl_reuse.rb:90:in `connect'
    from /usr/lib64/ruby/1.8/timeout.rb:53:in `timeout'
    from /usr/lib64/ruby/1.8/timeout.rb:101:in `timeout'
    from /home/afri/.gem/ruby/1.8/gems/net-http-persistent-2.7/lib/net/http/persistent/ssl_reuse.rb:90:in `connect'
    from /usr/lib64/ruby/1.8/net/http.rb:553:in `do_start'
    from /usr/lib64/ruby/1.8/net/http.rb:548:in `start'
    from /home/afri/.gem/ruby/1.8/gems/net-http-persistent-2.7/lib/net/http/persistent.rb:511:in `connection_for'
    from /home/afri/.gem/ruby/1.8/gems/net-http-persistent-2.7/lib/net/http/persistent.rb:806:in `request'
    from /home/afri/.gem/ruby/1.8/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:258:in `fetch'
    from /home/afri/.gem/ruby/1.8/gems/mechanize-2.5.1/lib/mechanize.rb:407:in `get'
    from ./inc/scbot.rb:165:in `update_sc_status'
    from ./inc/scbot.rb:144:in `on_privmsg'
    from /home/afri/.gem/ruby/1.8/gems/net-irc-0.0.9/lib/net/irc/client.rb:38:in `send'
    from /home/afri/.gem/ruby/1.8/gems/net-irc-0.0.9/lib/net/irc/client.rb:38:in `start'
    from ./start.rb:83
```

**Comment by donSchoe** [comment]
```
D, [2012-08-12T02:31:57.636767 #22638] DEBUG -- : RECEIVE: :qpx!~qpx@141.45.160.111 PRIVMSG #main-channel :.help
D, [2012-08-12T02:31:57.636981 #22638] DEBUG -- : SEND: PRIVMSG #main-channel :Type .np for current song or .stream for stream-url.
D, [2012-08-12T02:32:01.526904 #22638] DEBUG -- : RECEIVE: :qpx!~qpx@141.45.160.111 PRIVMSG #main-channel :.stream
D, [2012-08-12T02:32:01.527106 #22638] DEBUG -- : SEND: PRIVMSG #main-channel :Stream URL: http://example.com/listen.pls
D, [2012-08-12T02:32:07.263173 #22638] DEBUG -- : RECEIVE: :qpx!~qpx@141.45.160.111 PRIVMSG #main-channel :.prr
D, [2012-08-12T02:32:31.556709 #22638] DEBUG -- : RECEIVE: :qpx!~qpx@141.45.160.111 PRIVMSG #main-channel :.np
getaddrinfo: Name or service not known
/home/af./start.rb:84:in `<main>'-1.9.3-p194/gems/net-irc-0.0.9/lib/net/irc/client.rb:38:in `start'n `fetch'`request'on_for't' connect'
/home/afri/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.7/lib/net/http/persistent/ssl_reuse.rb:29:in `initialize': getaddrinfo: Name or service not known (SocketError)
    from /home/afri/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.7/lib/net/http/persistent/ssl_reuse.rb:29:in `open'
    from /home/afri/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.7/lib/net/http/persistent/ssl_reuse.rb:29:in `block in connect'
    from /home/afri/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
    from /home/afri/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
    from /home/afri/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.7/lib/net/http/persistent/ssl_reuse.rb:29:in `connect'
    from /home/afri/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
    from /home/afri/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:750:in `start'
    from /home/afri/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.7/lib/net/http/persistent.rb:511:in `connection_for'
    from /home/afri/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.7/lib/net/http/persistent.rb:806:in `request'
    from /home/afri/.rvm/gems/ruby-1.9.3-p194/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:258:in `fetch'
    from /home/afri/.rvm/gems/ruby-1.9.3-p194/gems/mechanize-2.5.1/lib/mechanize.rb:407:in `get'
    from inc/scbot.rb:165:in `update_sc_status'
    from inc/scbot.rb:144:in `on_privmsg'
    from /home/afri/.rvm/gems/ruby-1.9.3-p194/gems/net-irc-0.0.9/lib/net/irc/client.rb:38:in `start'
    from ./start.rb:84:in `<main>'
```

```
afri $ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
```

**Comment by donSchoe** [comment]
I REALLY NEED SLEEP LOL
